app/models.py
from app import db
import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.getTestUser()
  #    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
#    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    @staticmethod
    def getTestUser():
      return User(email='john@example.com', username='john', password='cat', id=0)

    @property
    def password(self):
      raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
      self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
      return check_password_hash(self.password_hash, password)


class Kedves(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    birth_ordinal = db.Column(db.Integer, nullable=False)

#    def __init__(self, name, birth_ordinal):
#        self.name = name
#        self.birth_ordinal = birth_ordinal

    def __repr__(self):
        return '<Kedves {} {}>'.format(self.name, datetime.date.fromordinal(self.birth_ordinal))

    def birth_date(self):
        return datetime.date.fromordinal(self.birth_ordinal)

    def days_diff(self, ref, year):
        offset = self.birth_date()
        return datetime.date(int(year), offset.month, offset.day).toordinal()-ref.birth_ordinal

app/forms.py
from flask.ext.wtf import Form
from wtforms import IntegerField, StringField, SelectField, DateField, SubmitField, PasswordField, BooleanField
#from wtforms.fields.html5 import DateField
from wtforms.validators import InputRequired, Email, Length, Regexp, Required, EqualTo
from .models import User
from wtforms import ValidationError

class LoginForm(Form):
    email = StringField('Email', validators=[InputRequired(), Length(1, 64),
                                             Email()])
    password = PasswordField('Password', validators=[InputRequired()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log In')

class RegistrationForm(Form):
    email = StringField('Email', validators=[Required(), Length(1, 64),
                                           Email()])
    username = StringField('Username', validators=[
        Required(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                          'Usernames must have only letters, '
                                          'numbers, dots or underscores')])
    password = PasswordField('Password', validators=[
        Required(), EqualTo('password2', message='Passwords must match.')])
    password2 = PasswordField('Confirm password', validators=[Required()])
    submit = SubmitField('Register')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')


class ReferenceForm(Form):
    year = IntegerField('year', validators=[InputRequired()])
    reference_id = SelectField('reference', coerce=int)

class KedvesForm(Form):
    name = StringField('name', validators=[InputRequired()])
    birth_date = DateField('birth_date', validators=[InputRequired()])

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask.ext.bootstrap import Bootstrap
from flask.ext.login import LoginManager


db = SQLAlchemy()
bootstrap = Bootstrap()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.login'


def create_app():
  app = Flask(__name__)
  app.config.from_object('config')
  bootstrap.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)

  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)

  return app


from app import models

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, flash, redirect, session, url_for, request, current_app
from app import db
from app.forms import KedvesForm, ReferenceForm
from app.models import Kedves
import datetime
from flask.ext.login import login_user, logout_user, login_required
from app.models import User
from app.forms import LoginForm, RegistrationForm
from . import main


@main.route('/login', methods=['GET', 'POST'])
def login():
  form = LoginForm()
  if form.validate_on_submit():
#      user = User.getTestUser()
#      login_user(user, form.remember_me.data)
#      return redirect(request.args.get('next') or url_for('.index'))


     user = User.query.filter_by(email=form.email.data).first()
     if user is not None and user.verify_password(form.password.data):
         login_user(user, form.remember_me.data)
         return redirect(request.args.get('next') or url_for('.index'))
     flash('Invalid username or password.')
  return render_template('login.html',
                         title='Login',
                         form=form)
                         
@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.login'))
    return render_template('register.html', form=form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('.index'))

@main.route('/')
@main.route('/index')
@login_required
def index():
  year = session.get('reference_year')
  if year is None:
    year = datetime.date.today().year # default
  ref_id = session.get('reference_id')
  if ref_id is None:
    ref = Kedves.query.filter_by(name=current_app.config['REFERENCE_NAME']).first() # default
  else:
    ref = Kedves.query.get(ref_id)
  kedves_list=Kedves.query.all()
  return render_template('index.html',
                           kedves_list=kedves_list,
                           year=year,
                           ref=ref)

@main.route('/reference', methods=['GET', 'POST'])
@login_required
def reference():
  form = ReferenceForm()
  form.reference_id.choices=[(k.id, k.name) for k in Kedves.query.all()]
  if form.validate_on_submit():
    session['reference_id'] = form.reference_id.data
    session['reference_year'] = form.year.data
    return redirect(url_for('.index'))
  return render_template('reference.html',
                         title='Reference',
                         form=form)

@main.route('/create_kedves', methods=['GET', 'POST'])
@login_required
def create_kedves():
  form = KedvesForm()
  if form.validate_on_submit():
    name = form.name.data
    birth_ordinal = form.birth_date.data.toordinal()
    kedves = Kedves (name=name, birth_ordinal=birth_ordinal)
    db.session.add(kedves)
    db.session.commit()
    flash("New kedves '{}' was successfully added".format(name))
    return redirect(url_for('.index'))
  return render_template('create_kedves.html',
                         title='Create',
                         form=form)

@main.route('/delete_kedves/<id>', methods=['POST', 'GET'])
@login_required
def delete_kedves(id):
  kedves = Kedves.query.get(id)
  db.session.delete(kedves)
  db.session.commit()
  flash('deleted')
  return redirect(url_for('.index'))

@main.route('/edit_kedves/<id>', methods=['POST', 'GET'])
@login_required
def edit_kedves(id):
  form = KedvesForm()
  kedves = Kedves.query.get(id)
  if form.validate_on_submit():
    kedves.name = form.name.data
    kedves.birth_ordinal = form.birth_date.data.toordinal()
    db.session.commit()
    flash('modified')
    return redirect(url_for('.index'))
  return render_template('edit_kedves.html',
                         form=form,
                         title='Edit',
                         kedves=kedves)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
  {% if title %}
    {{ title }} - MORZSI
  {% else %}
    MORZSI
  {% endif %}
{% endblock %}

{% block metas %}
  {{ super() }}
  <meta charset="UTF-8">
{% endblock %}


{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="/static/tables.css" />
  <link href="/static/bower_components/air-datepicker/dist/css/datepicker.min.css" rel="stylesheet" type="text/css">
  <script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
  <script src="/static/bower_components/air-datepicker/dist/js/datepicker.min.js"></script>

  <!-- Include English language -->
  <script src="/static/bower_components/air-datepicker/dist/js/i18n/datepicker.en.js"></script>
{% endblock %}

{% block navbar %}
  <div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
             data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">MORZSI Days</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/index">Home</a></li>
                <li><a href="/reference">Reference</a></li>
                <li><a href="/create_kedves">Create</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                  <li><a href="{{ url_for('main.logout') }}">Sign Out</a></li>
                {% else %}
                   <li><a href="{{ url_for('main.login') }}">Sign In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
  </div>
{% endblock %}

app/templates/base_old.html
<html>
  <head>
    {% if title %}
    <title>{{ title }} - MORZSI</title>
    {% else %}
    <title>MORZSI</title>
    {% endif %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
      .container {
        max-width: 500px;
        padding-top: 100px;
      }
    </style>
    <link rel="stylesheet" href="/static/tables.css" />
    <link href="/static/bower_components/air-datepicker/dist/css/datepicker.min.css" rel="stylesheet" type="text/css">
    <script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/static/bower_components/air-datepicker/dist/js/datepicker.min.js"></script>

    <!-- Include English language -->
    <script src="/static/bower_components/air-datepicker/dist/js/i18n/datepicker.en.js"></script>

  </head>
  <body>
    <div><a href="/index">Home</a> <a href="/reference">Reference</a> <a href="/create_kedves">Create</a></div>
    <hr>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul>
        {% for message in messages %}
            <li>{{ message }} </li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
  </body>
</html>

app/templates/create_kedves.html
{% extends "base.html" %}

{% block page_content %}
<div class="container">
  <div class="page-header">
    <h1>New Kedves</h1>
  </div>
  <form action="" method="post" name="create_kedves">
      {{ form.hidden_tag() }}
      <p>
          <label for="name">Name:</label>
          {{ form.name(size=15) }}<br>
          {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}<br>
      </p>
          <label for="birth_date">Birth date:</label>
           {{ form.birth_date(class='datepicker-here') }}
           <script>
           $('#birth_date').datepicker({
             language: 'en',
             dateFormat: 'yyyy-mm-dd'
           })
           </script>
          <br>
          {% for error in form.birth_date.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}<br>

        <button name="submit" type="submit">Add</button>
  </form>
</div>
{% endblock %}

app/templates/edit_kedves.html
{% extends "base.html" %}

{% block page_content %}
<div class="container">
  <div class="page-header">
    <h1>Edit Kedves</h1>
  </div>
  <form action="" method="post" name="edit_kedves">
      {{ form.hidden_tag() }}
      <p>
          <label for="name">Name:</label>
          {{ form.name(size=15,value=kedves.name) }}
          <br>
          {% for error in form.name.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}<br>
      </p>
      <p>
          <label for="birth_date">Birth date:</label>
          {{ form.birth_date(class='datepicker-here') }}
           <script>
           $('#birth_date').datepicker({
             language: 'en',
             dateFormat: 'yyyy-mm-dd'
           })
           var datepicker = $('#birth_date').datepicker().data('datepicker');
           var birthDate = new Date({{kedves.birth_date().year}},
                                    {{kedves.birth_date().month-1}},
                                    {{kedves.birth_date().day}});
           datepicker.selectDate(birthDate);
           </script>
          <br>
          {% for error in form.birth_date.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}<br>
      </p>

      <p><input type="submit" value="Save"></p>
  </form>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block page_content %}
    <div class="container">
      <div class="page-header">
        <h1>Kedvesek and {{ref.name}} days in {{year}}:</h1>
      </div>
      <table class="gridtable">
        <tr>
          <th>Kedves</th>
          <th>Date of birth</th>
          <th>Days</th>
        </tr>
        {% for kedves in kedves_list %}
        <tr>
          <td>{{kedves.name}}</td>
          <td>{{kedves.birth_date()}}</td>
          <td>{{kedves.days_diff(ref,year)}}</td>
          <td><a href="{{ url_for('main.edit_kedves', id=kedves.id) }}">edit</a></td>
          <td><a href="{{ url_for('main.delete_kedves', id=kedves.id) }}">delete</a></td>
        </tr>
        {% endfor %}
      </table>
    </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Login</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }} 
    <br>
    <p>New user? <a href="{{ url_for('main.register') }}">Click here to register</a>.</p>

</div>
{% endblock %}

app/templates/reference.html
{% extends "base.html" %}

{% block page_content %}
<div class="container">
  <div class="page-header">
    <h1>Parameters</h1>
  </div>
  <form action="" method="post" name="reference">
      {{ form.hidden_tag() }}
        <p>
          <label for="reference_id">Reference: </label>
          {{ form.reference_id }} <br>
          {% for error in form.reference_id.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}<br>
        </p>
      <p>
          <label for="year">Which year: </label>
          {{ form.year(size=6) }}<br>
          {% for error in form.year.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}<br>
      </p>
      <p><input type="submit" value="Days?"></p>
  </form>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Register{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Register</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}